### ISSUE TITLE
PostgreSQL database my_geonode changing password

### ISSUE THREAD

**Issue by Darkonyks** [GeoNode/geonode-project#167]
I have docker installation of GeoNode with all defaults: my_geonode, my_geonode_data etc. Now I'm truing to change default password for user my_geonode in PostgreSQL and i did. Also I have change in .env file to new password

_GEONODE_DATABASE=my_geonode
GEONODE_DATABASE_PASSWORD="my new password"_

I' m not sure if this is an issue but after changing password geonode is not able to start:

_psql: FATAL:  password authentication failed for user "my_geonode"
my_geonode is unavailable - sleeping_

I' m not sure if this is an issue or not but I do not now where else this new password should also be placed.

Please I need your help!

**Comment by vijdz** [comment]
I saw your question on gis.stackexchange and answered it. Here is probably not the right place to ask this, I mean not a real issue =)

**Comment by Darkonyks** [comment]
Thank you for your answer, this was very helpful. Because this is not a real issue I will close it.

**Comment by t-book** [comment]
Hi @vidlb head over to https://gitter.im/GeoNode/general This is where most devs mingle ;)

**Comment by t-book** [comment]
... and to your question try something like:

untested but try to alter the password directly in your db and set matching in .env

```
docker exec -i db4YOUR_GEONODE psql -d YOUR_GEONODE -U postgres -c "alter user YOUR_GEONODE_USER with password '<NEW_PASSWORD>';"
```

(replace capital words with correct information). repeat the same for geonode_data database.

**Comment by Darkonyks** [comment]
Thank you for suggestion's I had tried but had no luck. 
```
248128025af9   geonode/geonode:3.1        "/bin/sh -c 'service…"   4 minutes ago   Up 4 seconds                   8000/tcp                                              celery4geonode
04eee68c07a0   geonode/geonode:3.1        "/bin/sh -c 'service…"   4 minutes ago   Restarting (1) 6 seconds ago                                                         django4geonode
```

Next to do is to create my own Dockerfile and container as @vidlb suggested on https://gis.stackexchange.com/questions/387821/geonode-postgresql-default-password/388819#388819

**Comment by t-book** [comment]
Sorry but I think this is overkill.
What is invoke.log telling you?


Why not do it like this. 
- Change your passwords in .env back as they're set in postgres.
- restart your stack and see if django goes up again.
- use psql to reset your password @ postgres
- change credentials in .env
- restart your stack

Note 1: Don't forget that you can just start the db service to update passwords
note 2. Don't forget to build Django again: `docker-compose up -d --build django`

**Comment by Darkonyks** [comment]
OK. So what I have done:
Return all to defaults: invoke.log
```
GeoServer API are available!
GeoServer is available for HTTP calls!
********************geoserver fixture********************************
Setting GeoServer Admin Password...
Response Code: 200
GeoServer admin password updated SUCCESSFULLY!
***********************update admin details**************************
Installed 1 object(s) from 1 fixture(s)
```
Everything is up and running!

```
CONTAINER ID   IMAGE                      COMMAND                  CREATED         STATUS         PORTS                                                 NAMES
cdcf56f90760   geonode/geonode:3.1        "/bin/sh -c 'service…"   2 minutes ago   Up 2 minutes   8000/tcp                                              django4geonode
1e3c1b99cf5f   geonode/geonode:3.1        "/bin/sh -c 'service…"   2 minutes ago   Up 2 minutes   8000/tcp                                              celery4geonode
fabca9e04697   geonode/geoserver:2.17.2   "/usr/local/tomcat/t…"   3 minutes ago   Up 2 minutes   8080/tcp                                              geoserver4geonode
7d59e9837258   geonode/postgis:latest     "docker-entrypoint.s…"   3 minutes ago   Up 3 minutes   5432/tcp                                              db4geonode
f9cbbdd3d6a4   geonode/nginx:production   "/docker-entrypoint.…"   7 days ago      Up 7 days      0.0.0.0:80->80/tcp                                    nginx4geonode
059b1edeff5d   rabbitmq                   "docker-entrypoint.s…"   7 days ago      Up 7 days      4369/tcp, 5671-5672/tcp, 15691-15692/tcp, 25672/tcp   rabbitmq4geonode
```
Than I have run 
```
docker exec -i db4geonode psql -d geonode -U postgres -c "alter user geonode with password '123456';"
ALTER ROLE

docker exec -i db4geonode psql -d geonode_data -U postgres -c "alter user geonode_data with password '123456';"
ALTER ROLE
```
.env file in project folder contains only:
```
COMPOSE_PROJECT_NAME=geonode
SET_DOCKER_ENV=production
```
... but I have change all .env files in /opt/geonode/scripts/docker/env/production

db.env:
```
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
GEONODE_DATABASE=geonode
GEONODE_DATABASE_PASSWORD=123456 
GEONODE_GEODATABASE=geonode_data
GEONODE_GEODATABASE_PASSWORD=123456    
```
django.env:
```
DEBUG=False
DJANGO_SETTINGS_MODULE=geonode.settings
GEONODE_INSTANCE_NAME=geonode
GEONODE_LB_HOST_IP=localhost
GEONODE_LB_PORT=80

POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
GEONODE_DATABASE=geonode
GEONODE_DATABASE_PASSWORD=123456
GEONODE_GEODATABASE=geonode_data
GEONODE_GEODATABASE_PASSWORD=123456

GEONODE_DATABASE_SCHEMA=public
GEONODE_GEODATABASE_SCHEMA=public
DATABASE_URL=postgresql://geonode:geonode@db:5432/geonode
GEODATABASE_URL=postgis://geonode_data:geonode_data@db:5432/geonode_data

GEONODE_DB_CONN_MAX_AGE=0
GEONODE_DB_CONN_TOUT=5

ASYNC_SIGNALS=True
BROKER_URL=amqp://guest:guest@rabbitmq:5672/
```
Than I hit docker-compose up -d --build django
```
Successfully built f04751dd2b31
Successfully tagged geonode/geonode:3.1
Starting gsconf4geonode ... 
Starting gsconf4geonode ... done
Recreating db4geonode   ... done
geoserver4geonode is up-to-date
Recreating django4geonode ... done
```
After that: tail -F -n 300 invoke.log 
```
EONODE_DATABASE_SCHEMA=public
AVATAR_DEFAULT_URL=/geonode/img/avatar.png
ACCOUNT_OPEN_SIGNUP=True
DJANGO_EMAIL_HOST_PASSWORD=
HAYSTACK_SEARCH_RESULTS_PER_PAGE=200
DJANGO_SETTINGS_MODULE=geonode.settings
GEOSERVER_JAVA_OPTS=-Djava.awt.headless=true -Xms2G -Xmx4G -XX:+UnlockDiagnosticVMOptions -XX:+LogVMOutput -XX:LogFile=/var/log/jvm.log -XX:PerfDataSamplingInterval=500 -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:-UseGCOverheadLimit -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -Dfile.encoding=UTF8 -Djavax.servlet.request.encoding=UTF-8 -Djavax.servlet.response.encoding=UTF-8 -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=false -DGEOSERVER_CSRF_DISABLED=true -DPRINT_BASE_URL=http://geoserver:8080/geoserver/pdf -DALLOW_ENV_PARAMETRIZATION=true -Xbootclasspath/a:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/marlin-0.9.3-Unsafe.jar -Dsun.java2d.renderer=org.marlin.pisces.MarlinRenderingEngine
ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_APPROVAL_REQUIRED=False
SITEURL=http://localhost/
MEMCACHED_ENABLED=False
GEONODE_LB_HOST_IP=localhost
OAUTH2_CLIENT_ID=Jrchz2oPY3akmzndmgUTYrs9gczlgoV20YPSvqaV
API_LIMIT_PER_PAGE=1000
USER_ANALYTICS_ENABLED=True
DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
GEOSERVER_LOCATION=http://geoserver:8080/geoserver/
ACCOUNT_EMAIL_VERIFICATION=none
GEONODE_GEODATABASE_SCHEMA=public
HAYSTACK_SEARCH=False
GEONODE_INSTANCE_NAME=geonode
EMAIL_ENABLE=False
SHLVL=1
OGC_REQUEST_POOL_MAXSIZE=10
POSTGRES_USER=postgres
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED=False
GEODATABASE_URL=postgis://geonode_data:geonode_data@db:5432/geonode_data
DJANGO_EMAIL_USE_TLS=False
DJANGO_EMAIL_HOST_USER=
MONITORING_HOST_NAME=geonode
GEONODE_GEODATABASE_PASSWORD=123456
IS_CELERY=false
PYTHON_PIP_VERSION=20.1.1
GEONODE_DATABASE_PASSWORD=123456
GEOSERVER_PUBLIC_LOCATION=http://localhost/geoserver/
GEONODE_DB_CONN_TOUT=5
CORS_ORIGIN_ALLOW_ALL=True
GEOSERVER_ADMIN_PASSWORD=geoserver
CREATE_LAYER=True
PYTHON_GET_PIP_SHA256=b3153ec0cf7b7bbf9556932aa37e4981c35dc2a2c501d70d91d2795aa532be79
GOOGLE_API_KEY=
GEOIP_PATH=/mnt/volumes/statics/geoip.db
GEONODE_CLIENT_LAYER_PREVIEW_LIBRARY=mapstore
OGC_REQUEST_BACKOFF_FACTOR=0.3
GEONODE_GEODATABASE=geonode_data
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/eff16c878c7fd6b688b9b4c4267695cf1a0bf01b/get-pip.py
FORCE_REINIT=false
MEMCACHED_LOCATION=127.0.0.1:11211
GEOSERVER_ADMIN_USER=admin
GEONODE_DATABASE=geonode
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEFAULT_ANONYMOUS_VIEW_PERMISSION=True
MONITORING_ENABLED=True
GEONODE_LB_PORT=80
AVATAR_PROVIDERS='avatar.providers.PrimaryAvatarProvider','avatar.providers.GravatarAvatarProvider','avatar.providers.DefaultAvatarProvider'
DOCKER_ENV=production
DOCKER_API_VERSION="1.24"
GEOSERVER_WEB_UI_LOCATION=http://localhost/geoserver/
DEFAULT_FROM_EMAIL='GeoNode <no-reply@geonode.org>'
ACCOUNT_CONFIRM_EMAIL_ON_GET=False
DEBUG=False
MEDIA_ROOT=/mnt/volumes/statics/uploaded/
OAUTH2_CLIENT_SECRET=rCnp5txobUo83EpQEblM8fVj3QT5zb5qRfxNsuPzCqZaiRyIoxM4jdgMiZKFfePBHYXCLd7B8NlkfDBY9HKeIQPcy5Cp08KQNpRHQbjpLItDHv12GvkSeXp6OxaUETv3
SESSION_EXPIRED_CONTROL_ENABLED=True
MONITORING_DATA_TTL=365
Public Hostname or IP is localhost
Public PORT is None
Can not delete the $HOME/.override_env file as it doesn't exists
****************************finalize env**********************************
ACCOUNT_EMAIL_CONFIRMATION_EMAIL=False
MODIFY_TOPICCATEGORY=True
X_FRAME_OPTIONS=ALLOW-FROM ALL
ASYNC_SIGNALS=True
DJANGO_EMAIL_USE_SSL=False
OGC_REQUEST_POOL_CONNECTIONS=10
DATABASE_URL=postgresql://geonode:geonode@db:5432/geonode
OAUTH2_API_KEY=
OGC_REQUEST_MAX_RETRIES=1
ADMIN_USERNAME=admin
API_LOCKDOWN=False
HOSTNAME=72e5c1008bda
PYTHON_VERSION=3.8.3
AUTO_ASSIGN_REGISTERED_MEMBERS_TO_REGISTERED_MEMBERS_GROUP_NAME=True
DJANGO_EMAIL_HOST=localhost
ENABLE_JSONP=true
POSTGRES_PASSWORD=postgres
TIME_ENABLED=True
CENTRALIZED_DASHBOARD_ENABLED=False
AVATAR_GRAVATAR_SSL=True
ALLOWED_HOSTS=['django', '*']
MONITORING_SERVICE_NAME=local-geonode
FAVORITE_ENABLED=True
USER_ANALYTICS_GZIP=True
MEMCACHED_LOCK_EXPIRE=3600
C_FORCE_ROOT=1
CACHE_BUSTING_STATIC_ENABLED=False
MOSAIC_ENABLED=False
DEFAULT_BACKEND_UPLOADER=geonode.importer
EXIF_ENABLED=True
LOCKDOWN_GEONODE=False
MAX_DOCUMENT_SIZE=2
MEMCACHED_BACKEND=django.core.cache.backends.memcached.MemcachedCache
PWD=/usr/src/geonode
BING_API_KEY=
ACCOUNT_AUTHENTICATION_METHOD=username_email
MEMCACHED_LOCK_TIMEOUT=10
HAYSTACK_ENGINE_INDEX_NAME=haystack
OGC_REQUEST_TIMEOUT=30
UWSGI_CMD=uwsgi --ini /usr/src/app/uwsgi.ini
DJANGO_EMAIL_PORT=25
DEFAULT_ANONYMOUS_DOWNLOAD_PERMISSION=True
STATIC_ROOT=/mnt/volumes/statics/static/
_=/usr/bin/env
CACHE_BUSTING_MEDIA_ENABLED=False
GEONODE_DB_CONN_MAX_AGE=0
TASTYPIE_APIKEY=
BROKER_URL=amqp://guest:guest@rabbitmq:5672/
ADMIN_EMAIL=admin@localhost
HOME=/root
LANG=C.UTF-8
DEFAULT_BACKEND_DATASTORE=datastore
CLIENT_RESULTS_LIMIT=5
outFormat=text/javascript
MAPBOX_ACCESS_TOKEN=
HAYSTACK_ENGINE_URL=http://elasticsearch:9200/
ADMIN_PASSWORD=admin
IS_FIRST_START=true
GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568
GEONODE_DATABASE_SCHEMA=public
AVATAR_DEFAULT_URL=/geonode/img/avatar.png
ACCOUNT_OPEN_SIGNUP=True
DJANGO_EMAIL_HOST_PASSWORD=
HAYSTACK_SEARCH_RESULTS_PER_PAGE=200
DJANGO_SETTINGS_MODULE=geonode.settings
GEOSERVER_JAVA_OPTS=-Djava.awt.headless=true -Xms2G -Xmx4G -XX:+UnlockDiagnosticVMOptions -XX:+LogVMOutput -XX:LogFile=/var/log/jvm.log -XX:PerfDataSamplingInterval=500 -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:-UseGCOverheadLimit -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -Dfile.encoding=UTF8 -Djavax.servlet.request.encoding=UTF-8 -Djavax.servlet.response.encoding=UTF-8 -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=false -DGEOSERVER_CSRF_DISABLED=true -DPRINT_BASE_URL=http://geoserver:8080/geoserver/pdf -DALLOW_ENV_PARAMETRIZATION=true -Xbootclasspath/a:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/marlin-0.9.3-Unsafe.jar -Dsun.java2d.renderer=org.marlin.pisces.MarlinRenderingEngine
ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_APPROVAL_REQUIRED=False
SITEURL=http://localhost/
MEMCACHED_ENABLED=False
GEONODE_LB_HOST_IP=localhost
OAUTH2_CLIENT_ID=Jrchz2oPY3akmzndmgUTYrs9gczlgoV20YPSvqaV
API_LIMIT_PER_PAGE=1000
USER_ANALYTICS_ENABLED=True
DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
GEOSERVER_LOCATION=http://geoserver:8080/geoserver/
ACCOUNT_EMAIL_VERIFICATION=none
GEONODE_GEODATABASE_SCHEMA=public
HAYSTACK_SEARCH=False
GEONODE_INSTANCE_NAME=geonode
EMAIL_ENABLE=False
SHLVL=1
OGC_REQUEST_POOL_MAXSIZE=10
POSTGRES_USER=postgres
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED=False
GEODATABASE_URL=postgis://geonode_data:geonode_data@db:5432/geonode_data
DJANGO_EMAIL_USE_TLS=False
DJANGO_EMAIL_HOST_USER=
MONITORING_HOST_NAME=geonode
GEONODE_GEODATABASE_PASSWORD=123456
IS_CELERY=false
PYTHON_PIP_VERSION=20.1.1
GEONODE_DATABASE_PASSWORD=123456
GEOSERVER_PUBLIC_LOCATION=http://localhost/geoserver/
GEONODE_DB_CONN_TOUT=5
CORS_ORIGIN_ALLOW_ALL=True
GEOSERVER_ADMIN_PASSWORD=geoserver
CREATE_LAYER=True
PYTHON_GET_PIP_SHA256=b3153ec0cf7b7bbf9556932aa37e4981c35dc2a2c501d70d91d2795aa532be79
GOOGLE_API_KEY=
GEOIP_PATH=/mnt/volumes/statics/geoip.db
GEONODE_CLIENT_LAYER_PREVIEW_LIBRARY=mapstore
OGC_REQUEST_BACKOFF_FACTOR=0.3
GEONODE_GEODATABASE=geonode_data
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/eff16c878c7fd6b688b9b4c4267695cf1a0bf01b/get-pip.py
FORCE_REINIT=false
MEMCACHED_LOCATION=127.0.0.1:11211
GEOSERVER_ADMIN_USER=admin
GEONODE_DATABASE=geonode
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEFAULT_ANONYMOUS_VIEW_PERMISSION=True
MONITORING_ENABLED=True
GEONODE_LB_PORT=80
AVATAR_PROVIDERS='avatar.providers.PrimaryAvatarProvider','avatar.providers.GravatarAvatarProvider','avatar.providers.DefaultAvatarProvider'
DOCKER_ENV=production
DOCKER_API_VERSION="1.24"
GEOSERVER_WEB_UI_LOCATION=http://localhost/geoserver/
DEFAULT_FROM_EMAIL='GeoNode <no-reply@geonode.org>'
ACCOUNT_CONFIRM_EMAIL_ON_GET=False
DEBUG=False
MEDIA_ROOT=/mnt/volumes/statics/uploaded/
OAUTH2_CLIENT_SECRET=rCnp5txobUo83EpQEblM8fVj3QT5zb5qRfxNsuPzCqZaiRyIoxM4jdgMiZKFfePBHYXCLd7B8NlkfDBY9HKeIQPcy5Cp08KQNpRHQbjpLItDHv12GvkSeXp6OxaUETv3
SESSION_EXPIRED_CONTROL_ENABLED=True
MONITORING_DATA_TTL=365
**************************databases*******************************
                                      List of databases
       Name       |  Owner   | Encoding |  Collate   |   Ctype    |     Access privileges     
------------------+----------+----------+------------+------------+---------------------------
 geonode          | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =Tc/postgres             +
                  |          |          |            |            | postgres=CTc/postgres    +
                  |          |          |            |            | geonode=CTc/postgres
 geonode_data     | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =Tc/postgres             +
                  |          |          |            |            | postgres=CTc/postgres    +
                  |          |          |            |            | geonode_data=CTc/postgres
 postgres         | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0        | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres              +
                  |          |          |            |            | postgres=CTc/postgres
 template1        | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres              +
                  |          |          |            |            | postgres=CTc/postgres
 template_postgis | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
(6 rows)

                                      List of databases
       Name       |  Owner   | Encoding |  Collate   |   Ctype    |     Access privileges     
------------------+----------+----------+------------+------------+---------------------------
 geonode          | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =Tc/postgres             +
                  |          |          |            |            | postgres=CTc/postgres    +
                  |          |          |            |            | geonode=CTc/postgres
 geonode_data     | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =Tc/postgres             +
                  |          |          |            |            | postgres=CTc/postgres    +
                  |          |          |            |            | geonode_data=CTc/postgres
 postgres         | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0        | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres              +
                  |          |          |            |            | postgres=CTc/postgres
 template1        | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres              +
                  |          |          |            |            | postgres=CTc/postgres
 template_postgis | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
(6 rows)

                                      List of databases
       Name       |  Owner   | Encoding |  Collate   |   Ctype    |     Access privileges     
------------------+----------+----------+------------+------------+---------------------------
 geonode          | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =Tc/postgres             +
                  |          |          |            |            | postgres=CTc/postgres    +
                  |          |          |            |            | geonode=CTc/postgres
 geonode_data     | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =Tc/postgres             +
                  |          |          |            |            | postgres=CTc/postgres    +
                  |          |          |            |            | geonode_data=CTc/postgres
 postgres         | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0        | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres              +
                  |          |          |            |            | postgres=CTc/postgres
 template1        | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres              +
                  |          |          |            |            | postgres=CTc/postgres
 template_postgis | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
(6 rows)

GeoNode databases are up - executing command
**************************migrations*******************************
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "geonode"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 101, in handle
    loader.check_consistent_history(connection)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 283, in check_consistent_history
    applied = recorder.applied_migrations()
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "geonode"
```
... env file looks like accept changes but here at the end of log is error and container keep restarting

```
72e5c1008bda   geonode/geonode:3.1        "/bin/sh -c 'service…"   3 minutes ago    Restarting (1) 34 seconds ago                                                         django4geonode
2d54c1dd936c   geonode/postgis:latest     "docker-entrypoint.s…"   4 minutes ago    Up 4 minutes                    5432/tcp                                              db4geonode
1e3c1b99cf5f   ed6af4b3b58f               "/bin/sh -c 'service…"   22 minutes ago   Up 22 minutes                   8000/tcp                                              celery4geonode
fabca9e04697   geonode/geoserver:2.17.2   "/usr/local/tomcat/t…"   22 minutes ago   Up 22 minutes                   8080/tcp                                              geoserver4geonode
f9cbbdd3d6a4   geonode/nginx:production   "/docker-entrypoint.…"   7 days ago       Up 7 days                       0.0.0.0:80->80/tcp                                    nginx4geonode
059b1edeff5d   rabbitmq                   "docker-entrypoint.s…"   7 days ago       Up 7 days                       4369/tcp, 5671-5672/tcp, 15691-15692/tcp, 25672/tcp   rabbitmq4geonode
```

**Comment by vijdz** [comment]
@t-book Thanks for the suggestion, I certainly will !
I'm not contributing to Geonode for now but I'd like to in the near future ! 
I just started my own geonode-project development and I saw some minor bugs, I will open an issue for that.

@Darkonyks it seems you're not changing the password the right way. I'm not 100% sure about that but you should edit the password with the postgres user using the postgres database, not in the geonode or geonode_data database.
Try with the postgres db, as suggested by t-book "use psql to reset your password @ postgres"

**Comment by Darkonyks** [comment]
@vidlb It is not problem with changing password in psql. Password is successfully changed and I manage to login to db using pgadmin providing new password, also geoserver is connected to geonode and geonode_data db with new passwords (layers ale listed) Disk Quota option in geoserver successfully is connected to geonode_data

![image](https://user-images.githubusercontent.com/8660091/109871266-52f40200-7c6b-11eb-91c4-547eecfaf915.png)

Problem is with django. Django somewhere / somehow does not accept new password or override it with defaults that are somewhere hard coded.

**Comment by vijdz** [comment]
Again not 100% sure but it seems to me that django is trying to connect with user postgres, not geonode.

**Comment by Darkonyks** [comment]
Maybe you are right but I did not change postgres password it is by default "postgres". And wallowing logs problem persist with geonode and geonode_data users.

**Comment by t-book** [comment]
Hi @Darkonyks please check your env vars inside the container to see what is actually in use. https://docs.djangoproject.com/en/3.1/ref/django-admin/#diffsettings can also shed light into (`./manage.py diffsettings --all`).

**Comment by vijdz** [comment]
May be I'm wrong, but I believe you can change users password when connected to the postgres database, and only this one, except if you've changed auth config in /etc.

**Comment by Darkonyks** [comment]
@t-book @vidlb Hi again. Just to inform everyone that we find what was wrong, well not so wrong then something that we jumped over some settings. First to thank you all for your time, effort and will to help. What I have did:

change password for geonode and geonode_data. Password can be changed thru pgadmin or with commands:
```
docker exec -i db4geonode psql -d geonode -U postgres -c "alter user geonode with password '654321';"
docker exec -i db4geonode psql -d geonode_data -U postgres -c "alter user geonode_data with password '654321';"
```
then the password should be changed in three files:
1. tasks.py
2. db.env
3. django.env
(or depending on instalactions just in .env file)

in tasks.py must be changed:
```
def _update_db_connstring():
    user = os.getenv('GEONODE_DATABASE', 'geonode')
    pwd = os.getenv('GEONODE_DATABASE_PASSWORD', '654321')
    dbname = os.getenv('GEONODE_DATABASE', 'geonode')
    connstr = 'postgres://{0}:{1}@db:5432/{2}'.format(
        user,
        pwd,
        dbname
    )
    return connstr

def _update_geodb_connstring():
    geouser = os.getenv('GEONODE_GEODATABASE', 'geonode_data')
    geopwd = os.getenv('GEONODE_GEODATABASE_PASSWORD', '654321')
    geodbname = os.getenv('GEONODE_GEODATABASE', 'geonode_data')
    geoconnstr = 'postgis://{0}:{1}@db:5432/{2}'.format(
        geouser,
        geopwd,
        geodbname
    )
    return geoconnstr

"db_url": os.environ.get('DATABASE_URL', 'postgres://geonode:654321@db:5432/geonode'),
"geodb_url": os.environ.get('GEODATABASE_URL', 'postgis://geonode_data:654321@db:5432/geonode_data'),
```
2. in db.env
```
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
GEONODE_DATABASE=geonode
GEONODE_DATABASE_PASSWORD=654321
GEONODE_GEODATABASE=geonode_data
GEONODE_GEODATABASE_PASSWORD=654321
```
3. in django.env
```
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
GEONODE_DATABASE=geonode
GEONODE_DATABASE_PASSWORD=654321
GEONODE_GEODATABASE=geonode_data
GEONODE_GEODATABASE_PASSWORD=654321

DATABASE_URL=postgresql://geonode:654321@db:5432/geonode
GEODATABASE_URL=postgis://geonode_data:654321@db:5432/geonode_data
```

then just run docker-compose up -d --build django
