### ISSUE TITLE
ERROR:  jenkins ports 50000 at docker-compose.yml  

### ISSUE THREAD

**Issue by SESMAPS** [GeoNode/geonode-project#329]
When trying to install the geonode in VPS, and bring me version 3.3.x, it happens that when creating the container, this error appears:

`docker-compose build --no-cache
WARNING: The COMPOSE_PROJECT_NAME variable is not set. Defaulting to a blank string.
WARNING: The HTTPS_HOST variable is not set. Defaulting to a blank string.
WARNING: The HTTP_HOST variable is not set. Defaulting to a blank string.
WARNING: The HTTPS_PORT variable is not set. Defaulting to a blank string.
WARNING: The HTTP_PORT variable is not set. Defaulting to a blank string.
WARNING: The LETSENCRYPT_MODE variable is not set. Defaulting to a blank string.
WARNING: The ADMIN_EMAIL variable is not set. Defaulting to a blank string.
WARNING: The POSTGRESQL_MAX_CONNECTIONS variable is not set. Defaulting to a blank string.
WARNING: The JENKINS_HTTP_PORT variable is not set. Defaulting to a blank string.
WARNING: The JENKINS_HTTPS_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.jenkins.ports contains an invalid type, it should be a number, or an object
services.jenkins.ports contains an invalid type, it should be a number, or an object
services.geonode.ports contains an invalid type, it should be a number, or an object
services.geonode.ports contains an invalid type, it should be a number, or an object
services.jenkins.ports value [':', ':', '50000:50000'] has non-unique elements
`
Ubuntu server 20.04 and without making any changes to the docker-compose.yml file. Following the instructions of [Geonode-project](https://github.com/GeoNode/geonode-project#start-your-server-using-docker)

**Comment by rafaelsa99** [comment]
I am having the same problem on Ubuntu 20.04.4 LTS. Any progress on this issue @SESMAPS ?

**Comment by frafra** [comment]
This happens when `.env` has not populated. See `README.md` on how to generate it using the helper script `create-envfile.py`.

**Comment by danielknopp** [comment]
> 

Following the README.md,  and I apply the script

 I do this script `python create-envfile.py -f /opt/core/geonode-project/file.json \
        --hostname localhost \
        --https \
        --email random@email.com \
        --geonodepwd gn_password \
        --geoserverpwd gs_password \
        --pgpwd pg_password \
        --dbpwd db_password \
        --geodbpwd _db_password \
        --clientid 12345 \
        --clientsecret abc123 `
        
        its showing the following ERROR:
        
        ERROR - File does not exists: /opt/core/geonode-project/file.json
Traceback (most recent call last):
  File "/home/itt-s-l-2/geo_itt/create-envfile.py", line 177, in <module>
    generate_env_file(args)
  File "/home/itt-s-l-2/geo_itt/create-envfile.py", line 60, in generate_env_file
    raise FileNotFoundError
FileNotFoundError

**Comment by danielknopp** [comment]
> This happens when `.env` has not populated. See `README.md` on how to generate it using the helper script `create-envfile.py`.

following the README.md this is happening.

ERROR - File does not exists: /opt/core/geonode-project/file.json
Traceback (most recent call last):
  File "/home/itt-s-l-2/geo_itt/create-envfile.py", line 177, in <module>
    generate_env_file(args)
  File "/home/itt-s-l-2/geo_itt/create-envfile.py", line 60, in generate_env_file
    raise FileNotFoundError
FileNotFoundError

**Comment by giohappy** [comment]
@danielknopp I suspect you're calling `create-envfile.py` with the `-f` option and with the path to a not existing `file.json` file. This options assumes that you have created that json file, 
The README reports an example:

```
{
  "hostname": "value",
  "https": "value",
  "email": "value",
  "geonodepwd": "value",
  "geoserverpwd": "value",
  "pgpwd": "value",
  "dbpwd": "value",
  "geodbpwd": "value",
  "clientid": "value",
  "clientsecret": "value"
} 
```

**Comment by danielknopp** [comment]
@giohappy  Yes I have use this code .

python create-envfile.py -f /opt/core/geonode-project/file.json \
        --hostname localhost \
        --https \
        --email random@email.com \
        --geonodepwd gn_password \
        --geoserverpwd gs_password \
        --pgpwd pg_password \
        --dbpwd db_password \
        --geodbpwd _db_password \
        --clientid 12345 \
        --clientsecret abc123 

I have created on the project file an .env file with copying that data, however the problem still persisting... probably as u said I m giving the wrong path-file? I try to correct it where is the geonode-project but still the same... so not sure really, where should be saved this .txt file and also which path has to be used.  Thanks in advance ! 

> @danielknopp I suspect you're calling `create-envfile.py` with the `-f` option and with the path to a not existing `file.json` file. This options assumes that you have created that json file, The README reports an example:
> 
> ```
> {
>   "hostname": "value",
>   "https": "value",
>   "email": "value",
>   "geonodepwd": "value",
>   "geoserverpwd": "value",
>   "pgpwd": "value",
>   "dbpwd": "value",
>   "geodbpwd": "value",
>   "clientid": "value",
>   "clientsecret": "value"
> } 
> ```

**Comment by XiaoYang943** [comment]
I am having the same problem on Ubuntu 18.04.
What should I do?
Thanks.

**Comment by XiaoYang943** [comment]
GeoNode does not use '3.3. x', but instead uses the latest version of '4.0. x'
