### ISSUE TITLE
Issues with paver tasks

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode-project#41]
In behalf of Julierme (keeping track of ml issues)

Dear GeoNode users,

I am setting a new geonode-project in a python virtualenv following [1]. While running all the command line, paver sync is hitting a error:

Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/geonode_project/my_geonode/my_geonode/urls.py", line 24, in <module>
    from geonode.urls import urlpatterns
  File "/home/geo/Envs/geonode_project/src/geonode/geonode/urls.py", line 89, in <module>
    url(r'^catalogue/', include('geonode.catalogue.urls')),
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/geo/Envs/geonode_project/src/geonode/geonode/catalogue/urls.py", line 22, in <module>
    from . import views
  File "/home/geo/Envs/geonode_project/src/geonode/geonode/catalogue/views.py", line 29, in <module>
    from pycsw import server
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/pycsw/__init__.py", line 35, in <module>
    __version__ = pkg_resources.require("pycsw")[0].version
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (xmltodict 0.9.2 (/home/geo/Envs/geonode_project/lib/python2.7/site-packages), Requirement.parse('xmltodict==0.10.2'), set(['pycsw']))

And paver start 

pavement.start
---> pavement.start_geoserver
cd /home/geonode_project/my_geonode/geoserver/data
java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
java -Xms512m -Xmx2048m -server -XX:+UseConcMarkSweepGC -XX:MaxPermSize=512m -DGEOSERVER_DATA_DIR=/home/geonode_project/my_geonode/geoserver/data -Dgeofence.dir=/home/geonode_project/my_geonode/geoserver/data/geofence -jar /home/geonode_project/my_geonode/downloaded/jetty-runner-9.4.7.v20170914.jar --port 8080 --log /home/geonode_project/my_geonode/geoserver/jetty.log /home/geonode_project/my_geonode/scripts/misc/jetty-runner.xml > /dev/null &
cd /home/geonode_project/my_geonode
Starting GeoServer on http://localhost:8080/geoserver/
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
2018-08-01 11:43:11.942:INFO::main: Logging initialized @483ms to org.eclipse.jetty.util.log.StdErrLog
2018-08-01 11:43:11.962:INFO:oejr.Runner:main: Runner
2018-08-01 11:43:12.832:INFO:oejs.Server:main: jetty-9.4.7.v20170914
2018-08-01 11:43:19.024:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2018-08-01 11:43:19.029:INFO:oejs.session:main: No SessionScavenger set, using defaults
2018-08-01 11:43:19.032:INFO:oejs.session:main: Scavenging every 660000ms
ago 01, 2018 11:43:20 AM it.geosolutions.imageio.gdalframework.GDALUtilities loadGDAL
WARNING: Failed to load the GDAL native libs. This is not a problem unless you need to use the GDAL plugins: they won't be enabled.
java.lang.UnsatisfiedLinkError: no gdaljni in java.library.path
ago 01, 2018 11:43:23 AM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'XStreamPersisterInitializer', but ApplicationContext is unset.
ago 01, 2018 11:43:23 AM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
ago 01, 2018 11:43:23 AM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
ago 01, 2018 11:43:23 AM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
2018-08-01 11:43:23.501:INFO:oejshC.geoserver:main: Initializing Spring root WebApplicationContext
ago 01, 2018 11:43:40 AM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'MonitorDAO', but ApplicationContext is unset.
ago 01, 2018 11:43:40 AM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
ago 01, 2018 11:43:40 AM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
ago 01, 2018 11:43:40 AM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
ago 01, 2018 11:43:42 AM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'GeoServerSecurityProvider', but ApplicationContext is unset.
ago 01, 2018 11:43:42 AM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
ago 01, 2018 11:43:42 AM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
ago 01, 2018 11:43:42 AM org.geoserver.platform.GeoServerExtensions checkContext
WARNING: Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
Security framework of XStream not initialized, XStream is probably vulnerable.
2018-08-01 11:44:34.666:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@19bb089b{/geoserver,file:///home/geonode_project/my_geonode/geoserver/geoserver/,AVAILABLE}{../geoserver}
2018-08-01 11:44:34.676:INFO:oejs.AbstractNCSARequestLog:main: Opened /home/geonode_project/my_geonode/geoserver/jetty.log
2018-08-01 11:44:34.716:INFO:oejs.AbstractConnector:main: Started ServerConnector@3934e643{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2018-08-01 11:44:34.721:INFO:oejs.Server:main: Started @83260ms
2018-08-01 11:44:35.206:INFO:oejshC.geoserver:qtp885284298-13: Initializing Spring FrameworkServlet 'dispatcher'
The logs are available at /home/geonode_project/my_geonode/geoserver/jetty.log
---> pavement.start_qgis_server
---> pavement.start_django
 python -W ignore manage.py runserver 0.0.0.0:8000 &
sleep 30
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7f616da7f7d0>
Traceback (most recent call last):
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/geonode_project/my_geonode/my_geonode/urls.py", line 24, in <module>
    from geonode.urls import urlpatterns
  File "/home/geo/Envs/geonode_project/src/geonode/geonode/urls.py", line 89, in <module>
    url(r'^catalogue/', include('geonode.catalogue.urls')),
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/geo/Envs/geonode_project/src/geonode/geonode/catalogue/urls.py", line 22, in <module>
    from . import views
  File "/home/geo/Envs/geonode_project/src/geonode/geonode/catalogue/views.py", line 29, in <module>
    from pycsw import server
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/pycsw/__init__.py", line 35, in <module>
    __version__ = pkg_resources.require("pycsw")[0].version
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/geo/Envs/geonode_project/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (xmltodict 0.9.2 (/home/geo/Envs/geonode_project/lib/python2.7/site-packages), Requirement.parse('xmltodict==0.10.2'), set(['pycsw']))
GeoNode is now available.

has anyone faced these issues and could give me a hint?

[1] https://github.com/geosolutions-it/geonode-project

**Comment by indeOWS** [comment]
Hi @afabiani 
Thank you very much for reporting the issue here.

**Comment by t-book** [comment]
I cannot reproduce that @juliermegeotube is this issue still up to date?

**Comment by indeOWS** [comment]
Hi Toni and Alessio,

Thank you very much for taking this issue to consideration.

Kind regards

Julierme
