### ISSUE TITLE
save map broken on 2.8 branch?

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode-project#49]
Hi,

I´ve just installed GeoNode project 2.8 on two different Mac boxes. After saving a map I'm getting following error:

```
Internal Server Error: /maps/new/data
Traceback (most recent call last):
  File "/Users/ts/Documents/env/my_project/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ts/Documents/env/my_project/src/geonode/geonode/maps/views.py", line 698, in new_map_json
    map_obj.save()
  File "/Users/ts/Documents/env/my_project/lib/python2.7/site-packages/polymorphic/models.py", line 82, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/Users/ts/Documents/env/my_project/lib/python2.7/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/ts/Documents/env/my_project/lib/python2.7/site-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Users/ts/Documents/env/my_project/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/ts/Documents/env/my_project/src/geonode/geonode/geoserver/signals.py", line 620, in geoserver_post_save_map
    create_gs_thumbnail(instance, overwrite=False)
  File "/Users/ts/Documents/env/my_project/src/geonode/geonode/geoserver/helpers.py", line 2004, in create_gs_thumbnail
    return implementation(instance, overwrite)
  File "/Users/ts/Documents/env/my_project/src/geonode/geonode/layers/utils.py", line 1024, in create_gs_thumbnail_geonode
    overwrite=overwrite, check_bbox=check_bbox)
  File "/Users/ts/Documents/env/my_project/src/geonode/geonode/layers/utils.py", line 974, in create_thumbnail
    image = _prepare_thumbnail_body_from_opts(request_body)
  File "/Users/ts/Documents/env/my_project/src/geonode/geonode/geoserver/helpers.py", line 1863, in _prepare_thumbnail_body_from_opts
    bbox_to_projection([float(coord) for coord in request_body['bbox']] + [request_body['srid'], ],
ValueError: could not convert string to float: None
```

I´ve tried with different test layers (shp boundaries, raster etc. from training). This does not happen when using master branch. (Will do another check on Ubuntu as well but assume something wrong with GS13 or helper.py)

**Comment by t-book** [comment]
This seems to come from utils.py . Paolos last PR 942e286  fix this issue on master:

the lines are:
``` 
# a map could be empty!
        if not instance.layers:
            return
```
 https://github.com/GeoNode/geonode/blob/942e286246111ff7b52d9cd2a8d85d05e30e7e2c/geonode/layers/utils.py#L992

@afabiani @francbartoli Would you kindly have a look at this and back port utils from master to 2.8, if no other reasons stand against it, thanks!

**Comment by t-book** [comment]
– this issue should be in geonode repository, sorry ! –

**Comment by t-book** [comment]
-tested on ubuntu 16.04 same behavior-

**Comment by afabiani** [comment]
@t-book yeps, will check today. Thanks.

**Comment by t-book** [comment]
as always, thanks Alessio!

**Comment by afabiani** [comment]
https://github.com/GeoNode/geonode/pull/4054

**Comment by t-book** [comment]
closed with PR from afabiani.
