### ISSUE TITLE
Layer and map objects have no-image thumbnails

### ISSUE THREAD

**Issue by francbartoli** [GeoNode/geonode-project#67]
The right thumbnail is generated and present in the metadata detail though while remote thumbnail complains about missing WIDTH and HEIGHT in the request parameters

**Comment by francbartoli** [comment]
The output from a docker-compose run shows an error from a celery task:

```log
celery4infomapnode | [2019-02-28 12:21:56,995: ERROR/ForkPoolWorker-3] Task geonode.geoserver.tasks.thumbnail_task[35ab9ff7-4527-4200-89ba-cf0a0e54ceba] raised unexpected: DoesNotExist('Layer matching query does not exist.',)
celery4infomapnode | Traceback (most recent call last):
celery4infomapnode |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
celery4infomapnode |     R = retval = fun(*args, **kwargs)
celery4infomapnode |   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
celery4infomapnode |     return self.run(*args, **kwargs)
celery4infomapnode |   File "/usr/src/geonode/geonode/geoserver/tasks.py", line 43, in thumbnail_task
celery4infomapnode |     instance = Layer.objects.get(id=instance_id)
celery4infomapnode |   File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
celery4infomapnode |     return getattr(self.get_queryset(), name)(*args, **kwargs)
celery4infomapnode |   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 380, in get
celery4infomapnode |     self.model._meta.object_name
celery4infomapnode | Exception: Layer matching query does not exist.
```

**Comment by frafra** [comment]
I can confirm, I have the same issue on spcgeonode.

**Comment by frafra** [comment]
I made a new test and run `git bisect`. I think I found the regression: https://github.com/GeoNode/geonode/commit/a18bbd447721a370772ebc030632f4e36a4e4262

```
a18bbd447721a370772ebc030632f4e36a4e4262 is the first bad commit
commit a18bbd447721a370772ebc030632f4e36a4e4262
Author: hisham waleed karam <hisham.karam@cartologic.com>
Date:   Wed Feb 6 23:11:30 2019 +0200

    add async_thumbnail to improve upload time

:040000 040000 bb3b95e9c40c356a46a8aa078bd10848ac948a79 69241e049c6c4e298eb7d4e4abe7fc0c49422c0a M      geonode
bisect run success
```

**Comment by afabiani** [comment]
@frafra the PR on GeoNode has been merged.
Whenever you have the chance to test this again, please remember to close the issue. Thanks.
