### ISSUE TITLE
django container crashes: missing dependency elasticsearch

### ISSUE THREAD

**Issue by dubst3pp4** [GeoNode/geonode-project#97]
Hello,
I'm new to GeoNode development and just followed [your instructions](http://docs.geonode.org/en/2.10.x/install/project/index.html#docker) to build docker containers to run a development version of GeoNode. Unfortunately the _django_ and _celery_ containers constantly crash because of a missing elasticsearch dependency:

```
django4my_geonode | Traceback (most recent call last):
django4my_geonode |   File "manage.py", line 31, in <module>
django4my_geonode |     execute_from_command_line(sys.argv)
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
django4my_geonode |     utility.execute()
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
django4my_geonode |     self.fetch_command(subcommand).run_from_argv(self.argv)
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
django4my_geonode |     self.execute(*args, **cmd_options)
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
django4my_geonode |     output = self.handle(*args, **options)
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 227, in handle
django4my_geonode |     self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/core/management/sql.py", line 53, in emit_post_migrate_signal
django4my_geonode |     **kwargs
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
django4my_geonode |     for receiver in self._live_receivers(sender)
django4my_geonode |   File "/usr/src/geonode/geonode/monitoring/__init__.py", line 38, in run_setup_hooks
django4my_geonode |     populate()
django4my_geonode |   File "/usr/src/geonode/geonode/monitoring/models.py", line 1813, in populate
django4my_geonode |     m.save()
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
django4my_geonode |     force_update=force_update, update_fields=update_fields)
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 848, in save_base
django4my_geonode |     update_fields=update_fields, raw=raw, using=using,
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
django4my_geonode |     for receiver in self._live_receivers(sender)
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/haystack/signals.py", line 51, in handle_save
django4my_geonode |     index = self.connections[using].get_unified_index().get_index(sender)
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 109, in __getitem__
django4my_geonode |     self.thread_local.connections[key] = load_backend(self.connections_info[key]['ENGINE'])(using=key)
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 60, in load_backend
django4my_geonode |     return import_class(full_backend_path)
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/haystack/utils/loading.py", line 27, in import_class
django4my_geonode |     module_itself = importlib.import_module(module_path)
django4my_geonode |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
django4my_geonode |     __import__(name)
django4my_geonode |   File "/usr/local/lib/python2.7/site-packages/haystack/backends/elasticsearch2_backend.py", line 23, in <module>
django4my_geonode |     Please refer to the documentation.")
django4my_geonode | haystack.exceptions.MissingDependency: The 'elasticsearch2' backend requires the                             installation of 'elasticsearch>=2.0.0,<3.0.0'.                             Please refer to the documentation.
```
I've build the images with

`docker-compose -f docker-compose.development.yml -f docker-compose.development.override.yml build --no-cache`

and started the containers with

`docker-compose -f docker-compose.development.yml -f docker-compose.development.override.yml up`

Am I missing something?

**Comment by afabiani** [comment]
Hi, just remove any container from `docker-compose.development.yml` or `docker-compose.development.override.yml` which is not listed on `docker-compose.yml`

However, this is a bug indeed. The overrides must be fixed.
